apiVersion: v1
kind: Service
metadata:
  name: $oracle_service_name
  labels:
    type: db
    env: $env
spec:
  ports:
  - port: 1521
    targetPort: 1521
  selector:
    name: $oracle_pod_name
    type: db
    env: $env
