apiVersion: v1
kind: ReplicationController 
metadata:
  name: $oracle_rc_name
  labels:
    type: db
    env: $env
spec:
  replicas: 2
  selector:
    name: $oracle_pod_name
  template:
    metadata:
      labels:
        name: $oracle_pod_name
    spec:
      containers:
      - image: $oracle_image
        name: $oracle_name
        labels:
          type: db
          env: $env
        resources:
          requests:
            cpu: 1
            memory: 2G 
        livenessProbe:
          exec:
            command:
            - sqlplus 
            - -L 
            - "$oracle_user/$oracle_pw@//$oracle_host:$oracle_port/$oracle_db"
