apiVersion: v1
kind: BuildConfig
metadata:
  name: $runner_build_name
  labels:
    type: runner
    env: $env
spec:
  source:
    git: 
      uri: git@github.com:cjvirtucio87/todo-rscript-oracle.git
      http_proxy: $http_proxy
      https_proxy: $https_proxy
      no_proxy: $no_proxy
    sourceSecret:
      name: $runner_ssh_secret_name
  strategy:
    dockerStrategy:
      dockerfilePath: $dockerfile_path 
      env:
      - name: "APP_ORACLE_HOST"
        value: "$app_oracle_host"
      - name: "APP_ORACLE_PORT"
        value: "$app_oracle_port"
      - name: "APP_ORACLE_DB"
        value: "$app_oracle_db"
      - name: "APP_ORACLE_USER"
        value: "$app_oracle_user"
      - name: "APP_ORACLE_PASSWORD"
        value: "$app_oracle_password"
      - name: "BUILD_LOGLEVEL"
        value: "5"
  resources:
    requests:
      cpu: 1
      memory: 2G
  output:
    to:
      kind: "ImageStreamTag"
      name: "$runner_image_name:$runner_image_version"
