apiVersion: batch/v1
kind: Job 
metadata:
  name: $runner_job_name
  labels:
    type: runner
    env: $env
spec:
  completions: 1 
  selector:
    name: $runner_pod_name
  template:
    metadata:
      labels:
        name: $runner_pod_name
    spec:
      restartPolicy: Never 
      containers:
      - image: "$registry_uri/$runner_image"
        name: $runner_name
        imagePullPolicy: Always
        labels:
          type: runner 
          env: $env
        resources:
          requests:
            cpu: 1
            memory: 2G 
